# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Optional (for classic Netlify Functions):
[functions]
  node_bundler = "esbuild"
  
[[edge_functions]]
  function = "seo"
  path = "/en/articles/*"

# Catch Arabic Articles
[[edge_functions]]
  function = "seo"
  path = "/ar/articles/*"

# Catch Kurdish Articles
[[edge_functions]]
  function = "seo"
  path = "/ckb/articles/*"

# SPA fallback: send all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
